# This workflow handles stopping an AWS EC2 hosts under the OpenRemote hosted zone
# You need to be a member of the CI/CD github team to use this
name: Stop Host

on:
  workflow_dispatch:
    inputs:
      HOST:
        description: 'Host to stop'
        required: true

  jobs:

provision:
  name: Stop
  runs-on: ubuntu-latest

  steps:

    - name: Check CI/CD team membership
      uses: tspascoal/get-user-teams-membership@v1
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        organization: openremote
        team: CI/CD
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_READING_ORG_TEAMS }} # Personal access token used to query github (Requires scope: `read:org`)

    - name: Stop Host
      if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
      run: .ci_cd/aws/stop_ec2_instance.sh "$HOST"
      env:
        HOST: ${{ github.event.inputs.HOST }}
        INSTANCE_TYPE: ${{ github.event.inputs.INSTANCE_TYPE }}
